name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
  
    # SETUP .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x.x
    - name: Restore fable
      run: dotnet tool restore

    # SETUP NODE
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
          node-version: 16
    - name: install node modules
      working-directory: ./
      run: npm install --ignore-scripts

    # SETUP PYTHON
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Setup Virtual Environment
      run: python -m venv .venv

    # BUILD
    - name: make script executable
      if: matrix.os == 'ubuntu-latest'
      run: chmod u+x build.sh
    - name: Test (Unix)
      if: matrix.os == 'ubuntu-latest'
      working-directory: ./
      run: ./build.sh runtests
    - name: Test (Windows)
      if: matrix.os == 'windows-latest'
      run: .\build.cmd runtests